### ISSUE TITLE
PA Review: Image Index

### ISSUE THREAD

**Issue by ashvalejohn** [ashvalejohn/catalog-app#10]
AKA Photo Roll
- [x] Feed of images
- [x] Images have corresponding clickable image maps
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by ashvalejohn** [comment]
- [ ] Add cuter loading text

**Comment by mladenoff** [comment]
This is really coming along nicely.
