### ISSUE TITLE
PA Review: Cart

### ISSUE THREAD

**Issue by ashvalejohn** [ashvalejohn/catalog-app#25]
- Users can: 
   - [x] see items in cart
   - [x] add items to cart
   - [x] remove items from cart
   - [x] update size of item cart
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by ashvalejohn** [comment]
@mladenoff

**Comment by mladenoff** [comment]
I don't get any kind of UI feedback if I try to add to cart without specifying a size.

**Comment by mladenoff** [comment]
When I am not logged in and I go to an item and select a size and 'add to cart' I get no feedback either. Shouldn't it prompt me for login and then add to cart on successful login?

**Comment by ashvalejohn** [comment]
@mladenoff 

- [x] Add errors when user forgets to select a size
- [x] Don't allow user to select a size or add to cart unless they're logged in

[Live on Heroku](http://ashvalejohn-full-stack.herokuapp.com/#/)

**Comment by ashvalejohn** [comment]
@mladenoff 

- [x] Redirect user back to selected item panel on login

[Live on Heroku](http://ashvalejohn-full-stack.herokuapp.com/#/)

**Comment by mladenoff** [comment]
This takes care of all the things we talked about on Slack. I think this looks MV.
