### ISSUE TITLE
PA Review Search

### ISSUE THREAD

**Issue by ashvalejohn** [ashvalejohn/catalog-app#39]
- [x] Users can search for a color or type of clothing item and photo roll will only show images that contain that item
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by ashvalejohn** [comment]
- [x] Add tags to image to expand search

[Live on Heroku](http://ashvalejohn-full-stack.herokuapp.com/#/)

**Comment by mladenoff** [comment]
I think your "back" could be more aesthetically pleasing, but this looks great.
